# Generated by Django 5.2.3 on 2025-06-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['price']},
        ),
    ]
