# Generated by Django 5.2.3 on 2025-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
