# Generated by Django 5.2.3 on 2025-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'delivery_methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=16)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=30)),
                ('apartament_number', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(default='Polska', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this your default address?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_address',
                'ordering': ['-is_default', '-modified_at'],
            },
        ),
    ]
