# Generated by Django 5.2.3 on 2025-10-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_deliverymethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='description',
        ),
    ]
