# Generated by Django 5.2.3 on 2025-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('payu', 'PayU'), ('p24', 'Przelewy24'), ('cod', 'Płatność przy odbiorze')], max_length=25)),
                ('fee_flat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
