# Generated by Django 5.2.3 on 2025-10-29 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not paid'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='not_paid', max_length=20)),
                ('shipping_first_name', models.CharField(max_length=50)),
                ('shipping_last_name', models.CharField(blank=True, max_length=80)),
                ('shipping_company_name', models.CharField(blank=True, max_length=500)),
                ('shipping_tax_number', models.CharField(blank=True, max_length=64)),
                ('shipping_street', models.CharField(max_length=255)),
                ('shipping_house_number', models.CharField(max_length=30)),
                ('shipping_apartament_number', models.CharField(blank=True, max_length=30)),
                ('shipping_postal_code', models.CharField(max_length=30)),
                ('shipping_city', models.CharField(max_length=150)),
                ('shipping_country', models.CharField(default='Polska', max_length=100)),
                ('shipping_phone', models.CharField(blank=True, max_length=30)),
                ('shipping_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveIntegerField()),
                ('variant_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
