# Generated by Django 5.2.3 on 2025-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=16)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=30)),
                ('apartament_number', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(default='Polska', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not paid'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='not_paid', max_length=20)),
                ('payment_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=10)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveIntegerField()),
                ('variant_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
