# Generated by Django 5.2.3 on 2025-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=16),
        ),
    ]
